# Generated by Django 3.1.5 on 2021-01-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReceiptNo', models.CharField(max_length=15, null=True, unique=True)),
                ('CompletioTime', models.CharField(max_length=30, null=True)),
                ('Details', models.CharField(max_length=100, null=True)),
                ('PaidIn', models.CharField(max_length=10, null=True)),
                ('Withdrawn', models.CharField(max_length=10, null=True)),
                ('Balance', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
