# Generated by Django 3.1.5 on 2021-01-22 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_transactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='CompletioTime',
            new_name='CompletionTime',
        ),
    ]
